package application.gui.main;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;

import java.net.URL;
import java.util.ResourceBundle;

import application.files.log;
import application.smartpost.smartpost;
import application.types.o_package;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextArea;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import javafx.scene.control.MenuButton;

public class gui_main implements Initializable{
	@FXML
	private Button btn_save, btn_load, btn_main_reset, btn_packages, btn_items, btn_add_route, btn_send, btn_add;

	@FXML
	private Label label_error;
	@FXML
	private TextArea text_area_log;
	@FXML
	private MenuButton button_menu;
	@FXML
	private MenuItem menu_button_settings, menu_button_close;
	@FXML
	private WebView screen_web;
	@FXML
	private ComboBox<String> cmb_post_offices, cmb_packages;

	private smartpost __smartpost;
	private WebEngine __engine;
	private log __log;

	
	@FXML
	public void gui_shipments_open()
	{
		try {
			Stage stage = new Stage();
	        Parent root = FXMLLoader.load(getClass().getResource("/application/gui/packages/gui_packages.fxml"));
	        
	        Scene scene = new Scene(root);
	        
	        //stage.initStyle(StageStyle.UNDECORATED);
	        stage.setResizable(false);
	        stage.setScene(scene);   
	        stage.show();
	        
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	@FXML
	public void gui_items_open()
	{
		try {
			Stage stage = new Stage();
	        Parent root = FXMLLoader.load(getClass().getResource("/application/gui/items/gui_items.fxml"));
	        
	        Scene scene = new Scene(root);
	        
	        //stage.initStyle(StageStyle.UNDECORATED);
	        stage.setResizable(false);
	        stage.setScene(scene);   
	        stage.show();
	        
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	@FXML
	public void add_post_to_map()
	{
		if (cmb_post_offices.getValue() == null)
			return;

		__smartpost.set_on_map(cmb_post_offices.getSelectionModel().getSelectedIndex(), __engine);
		cmb_post_offices.getSelectionModel().clearSelection();
	}
	
	@FXML
	public void action_send(ActionEvent e)
	{
		o_package __package = __smartpost.send_package(__engine, cmb_packages.getItems().indexOf(cmb_packages.getValue()));
		
		if (__package == null)
			return;
		
		double dist = __smartpost.draw_path(__engine, __package);
		
		__log.add_entry(dist, __package, true);
	}
	
	// Event Listener on Button[#button_save].onAction
	@FXML
	public void action_save_to_file(ActionEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on Button[#button_load].onAction
	@FXML
	public void action_load_from_file(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void action_close(ActionEvent event) {
		Platform.exit();
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		__engine = screen_web.getEngine();
		__engine.load(getClass().getResource("html/index.html").toExternalForm());
		
		__smartpost = smartpost.getInstance();
		__smartpost.retrieve_all();
		__smartpost.populate(cmb_post_offices, false);

	}
	
}
